// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yteqtbfmykltxzdcbpsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZXF0YmZteWtsdHh6ZGNicHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjU0MzcsImV4cCI6MjA1NzM0MTQzN30.snlDSxo8y0mCWgrwShuX6XIlj8XTqblpBAOEzJXwAh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);